import { FoodItem } from "./types";

export const INITIAL_FOOD_DATABASE: FoodItem[] = [
  // --- THỰC VẬT (PLANT BASED) ---
  {
    id: "plant_banana",
    name: "Chuối chín",
    type: "plant",
    category: "Trái cây",
    calories: 89,
    potassium: 358,
    protein: 1.1,
    fat: 0.3,
    carbs: 22.8,
    servingSizeInfo: "1 quả trung bình (~120g)",
    description: "Nguồn cung cấp năng lượng nhanh, rất giàu Kali tốt cho cơ bắp và huyết áp."
  },
  {
    id: "plant_avocado",
    name: "Quả bơ",
    type: "plant",
    category: "Trái cây",
    calories: 160,
    potassium: 485,
    protein: 2.0,
    fat: 14.7,
    carbs: 8.5,
    servingSizeInfo: "1 nửa quả bơ (~100g)",
    description: "Giàu chất béo lành mạnh không bão hòa đơn và cực kỳ dồi dào Kali."
  },
  {
    id: "plant_spinach",
    name: "Cải bó xôi (Rau Bina)",
    type: "plant",
    category: "Rau xanh",
    calories: 23,
    potassium: 558,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    servingSizeInfo: "1 bát nhỏ chín (~100g)",
    description: "Tỷ lệ Kali cực cao, dồi dào sắt và vitamin A/C. Cần lưu ý cho người bệnh thận."
  },
  {
    id: "plant_potato",
    name: "Khoai tây hấp/luộc",
    type: "plant",
    category: "Củ & Hạt",
    calories: 87,
    potassium: 379,
    protein: 1.9,
    fat: 0.1,
    carbs: 20.1,
    servingSizeInfo: "1 củ vừa (~150g)",
    description: "Tinh bột tiêu hóa chậm lành mạnh, hàm lượng Kali dồi dào có trong vỏ và thịt củ."
  },
  {
    id: "plant_broccoli",
    name: "Súp lơ xanh (Bông cải luộc)",
    type: "plant",
    category: "Rau xanh",
    calories: 34,
    potassium: 316,
    protein: 2.8,
    fat: 0.4,
    carbs: 6.6,
    servingSizeInfo: "1 bát vừa (~100g)",
    description: "Chất xơ cao, giàu Kali và vitamin K chống oxy hóa tốt."
  },
  {
    id: "plant_water_spinach",
    name: "Rau muống luộc",
    type: "plant",
    category: "Rau xanh",
    calories: 19,
    potassium: 122,
    protein: 2.0,
    fat: 0.2,
    carbs: 3.1,
    servingSizeInfo: "1 đĩa nhỏ (~100g)",
    description: "Rau quốc dân Việt Nam, thanh mát cơ thể, lượng Kali ở mức vừa phải lý tưởng."
  },
  {
    id: "plant_tomato",
    name: "Cà chua tươi",
    type: "plant",
    category: "Rau xanh",
    calories: 18,
    potassium: 237,
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
    servingSizeInfo: "1 quả trung bình (~100g)",
    description: "Chứa Lycopene chống oxy hóa ưu việt, tốt cho tim mạch và làm sáng mịn làn da."
  },
  {
    id: "plant_guava",
    name: "Quả ổi chín",
    type: "plant",
    category: "Trái cây",
    calories: 68,
    potassium: 417,
    protein: 2.6,
    fat: 1.0,
    carbs: 14.3,
    servingSizeInfo: "1 quả vừa (~150g)",
    description: "Cực kỳ dồi dào Vitamin C và chất xơ hòa tan, giúp kiểm soát đường huyết và huyết áp tốt."
  },
  {
    id: "plant_orange",
    name: "Quả cam ngọt",
    type: "plant",
    category: "Trái cây",
    calories: 47,
    potassium: 181,
    protein: 0.9,
    fat: 0.1,
    carbs: 11.8,
    servingSizeInfo: "1 quả (~150g)",
    description: "Nguồn bổ sung nước tinh khiết, tăng cường đề kháng tự nhiên hữu hiệu."
  },
  {
    id: "plant_watermelon",
    name: "Dưa hấu tươi",
    type: "plant",
    category: "Trái cây",
    calories: 30,
    potassium: 112,
    protein: 0.6,
    fat: 0.2,
    carbs: 7.6,
    servingSizeInfo: "1 miếng vừa (~150g)",
    description: "Giải khát bù nước tuyệt vời, có hàm lượng Kali thấp tương đối an toàn cho hệ Thận."
  },
  {
    id: "plant_pumpkin",
    name: "Bí đỏ hấp",
    type: "plant",
    category: "Rau xanh",
    calories: 26,
    potassium: 340,
    protein: 1.0,
    fat: 0.1,
    carbs: 6.5,
    servingSizeInfo: "1 bát nhỏ (~100g)",
    description: "Chứa hàm lượng cao beta-carotene bổ mắt, Kali dồi dào tốt cho huyết áp và tuần hoàn."
  },
  {
    id: "plant_papaya",
    name: "Đu đủ chín",
    type: "plant",
    category: "Trái cây",
    calories: 43,
    potassium: 182,
    protein: 0.5,
    fat: 0.3,
    carbs: 10.8,
    servingSizeInfo: "1 miếng mỏng (~100g)",
    description: "Dồi dào enzyme papain giúp phân giải protein động vật dứt điểm, êm nhẹ dạ dày."
  },
  {
    id: "plant_bitter_melon",
    name: "Khổ qua (Mướp đắng)",
    type: "plant",
    category: "Rau xanh",
    calories: 17,
    potassium: 296,
    protein: 1.0,
    fat: 0.2,
    carbs: 3.7,
    servingSizeInfo: "1 quả nhỏ (~100g)",
    description: "Hỗ trợ ổn định đường huyết, kích hoạt insulin tự nhiên cho cơ thể."
  },
  {
    id: "plant_carrot",
    name: "Cà rốt luộc",
    type: "plant",
    category: "Rau xanh",
    calories: 41,
    potassium: 320,
    protein: 0.9,
    fat: 0.2,
    carbs: 9.6,
    servingSizeInfo: "1 củ vừa (~100g)",
    description: "Thực phẩm vàng cho đôi mắt sáng khỏe và hệ miễn dịch dẻo dai."
  },
  {
    id: "plant_cabbage",
    name: "Bắp cải luộc",
    type: "plant",
    category: "Rau xanh",
    calories: 25,
    potassium: 170,
    protein: 1.3,
    fat: 0.1,
    carbs: 5.8,
    servingSizeInfo: "1 bát vừa (~100g)",
    description: "Chất xơ cao, lượng Kali thấp hoàn hảo, là lựa chọn số 1 cho người dưỡng bệnh bộc lộ hệ Thận."
  },
  {
    id: "plant_oats",
    name: "Yến mạch nguyên cám",
    type: "plant",
    category: "Tinh bột",
    calories: 389,
    potassium: 429,
    protein: 16.9,
    fat: 6.9,
    carbs: 66.3,
    servingSizeInfo: "1 bát nhỏ nấu chín (~50g khô)",
    description: "Yến mạch vô cùng dồi dào chất xơ beta-glucan giảm cholesterol, protein tốt và giàu kali cải thiện tim mạch."
  },
  {
    id: "plant_sweet_potato",
    name: "Khoai lang luộc",
    type: "plant",
    category: "Củ & Hạt",
    calories: 86,
    potassium: 337,
    protein: 1.6,
    fat: 0.1,
    carbs: 20.1,
    servingSizeInfo: "1 củ vừa (~150g)",
    description: "Tinh bột tiêu hóa chậm, chỉ số đường huyết GI thấp, dồi dào Vitamin A và Kali hỗ trợ sức khỏe cơ bắp."
  },
  {
    id: "plant_canna_noodles",
    name: "Miến dông chín",
    type: "plant",
    category: "Tinh bột",
    calories: 95,
    potassium: 10,
    protein: 0.1,
    fat: 0.0,
    carbs: 23.5,
    servingSizeInfo: "1 bát miến chín (~150g)",
    description: "Miến làm từ tinh bột củ dông ta, cực kỳ ít Kali và đạm, đặc biệt tuyệt vời cho người suy thận cần giảm áp lực lọc."
  },
  {
    id: "plant_kudzu_starch",
    name: "Bột sắn dây chín",
    type: "plant",
    category: "Tinh bột",
    calories: 110,
    potassium: 15,
    protein: 0.1,
    fat: 0.0,
    carbs: 27.0,
    servingSizeInfo: "1 cốc nước sắn dây ấm (~200ml)",
    description: "Bột sắn dây có tính chất giải nhiệt cao, kali cực kỳ thấp, đặc biệt an toàn và dịu nhẹ với thận và dạ dày."
  },
  {
    id: "plant_chayote",
    name: "Su su luộc",
    type: "plant",
    category: "Rau xanh",
    calories: 19,
    potassium: 125,
    protein: 0.8,
    fat: 0.1,
    carbs: 4.5,
    servingSizeInfo: "1 bát nhỏ (~100g)",
    description: "Vị ngọt thanh dịu mát, rất lý tưởng để nạp ít Calo, dồi dào folate và có lượng kali ở mức trung bình thấp an tâm."
  },
  {
    id: "plant_kohlrabi",
    name: "Su hao luộc",
    type: "plant",
    category: "Rau xanh",
    calories: 27,
    potassium: 350,
    protein: 1.7,
    fat: 0.1,
    carbs: 6.2,
    servingSizeInfo: "1 bát su hao thái sợi (~100g)",
    description: "Cực kỳ giàu Vitamin C tăng sức đề kháng và dồi dào chất xơ. Kali thuộc nhóm cao, người bệnh thận nên lưu ý chia nhỏ bữa."
  },
  {
    id: "plant_cucumber",
    name: "Dưa leo tươi",
    type: "plant",
    category: "Rau xanh",
    calories: 15,
    potassium: 147,
    protein: 0.6,
    fat: 0.1,
    carbs: 3.6,
    servingSizeInfo: "1 quả dưa leo (~120g)",
    description: "Cấp nước tự nhiên vô cùng dồi dào, calories gần như bằng không, hàm lượng kali dịu nhẹ phù hợp mọi chế độ."
  },
  {
    id: "plant_bread",
    name: "Bánh mì gối trắng",
    type: "plant",
    category: "Tinh bột",
    calories: 265,
    potassium: 115,
    protein: 9.0,
    fat: 3.2,
    carbs: 49.0,
    servingSizeInfo: "2 lát bánh mì (~50g)",
    description: "Nguồn tinh bột nhanh ăn liền thuận tiện cho bữa sáng, kali ở mức tương đối thấp an toàn."
  },
  {
    id: "plant_grapes",
    name: "Nho chín tươi",
    type: "plant",
    category: "Trái cây",
    calories: 69,
    potassium: 191,
    protein: 0.7,
    fat: 0.2,
    carbs: 18.1,
    servingSizeInfo: "1 chùm nhỏ (~100g)",
    description: "Chứa dồi dào chất chống oxy hóa Resveratrol cực tốt cho động mạch tim và hỗ trợ tuần hoàn máu."
  },
  {
    id: "plant_blueberries",
    name: "Quả Việt quất tươi",
    type: "plant",
    category: "Trái cây",
    calories: 57,
    potassium: 77,
    protein: 0.7,
    fat: 0.3,
    carbs: 14.5,
    servingSizeInfo: "1 chén nhỏ (~100g)",
    description: "Siêu thực phẩm chống oxy hóa cực mạnh, bảo vệ tế bào não. Sở hữu mức Kali cực thấp, an toàn bậc nhất cho bệnh Thận."
  },
  {
    id: "plant_tofu",
    name: "Đậu hũ trắng",
    type: "plant",
    category: "Đậu & Hạt",
    calories: 76,
    potassium: 121,
    protein: 8.0,
    fat: 4.8,
    carbs: 1.9,
    servingSizeInfo: "1 miếng nhỏ (~100g)",
    description: "Đạm thực vật tuyệt vời chất lượng cao, ít béo no, an toàn cho tim mạch."
  },
  {
    id: "plant_white_rice",
    name: "Cơm trắng",
    type: "plant",
    category: "Tinh bột",
    calories: 130,
    potassium: 35,
    protein: 2.7,
    fat: 0.3,
    carbs: 28.0,
    servingSizeInfo: "1 bát cơm (~100g)",
    description: "Nguồn tinh bột và năng lượng chủ yếu tại Việt Nam, lượng Kali rất thấp, an toàn cho bệnh thận."
  },
  {
    id: "plant_cashew",
    name: "Hạt điều sấy khô",
    type: "plant",
    category: "Đậu & Hạt",
    calories: 553,
    potassium: 660,
    protein: 18.2,
    fat: 43.8,
    carbs: 30.1,
    servingSizeInfo: "1 nắm nhỏ (~30g)",
    description: "Giàu đạm thực vật, chất béo tốt và khoáng chất, lượng calories cao nên cân đối."
  },
  {
    id: "plant_apple",
    name: "Táo đỏ tươi",
    type: "plant",
    category: "Trái cây",
    calories: 52,
    potassium: 107,
    protein: 0.3,
    fat: 0.2,
    carbs: 13.8,
    servingSizeInfo: "1 quả vừa (~150g)",
    description: "Trái cây tuyệt vời giàu chất xơ hòa tan (Pectin), có lượng Kali thấp an toàn."
  },
  {
    id: "plant_black_bean",
    name: "Đậu đen chín",
    type: "plant",
    category: "Đậu & Hạt",
    calories: 132,
    potassium: 355,
    protein: 8.9,
    fat: 0.5,
    carbs: 23.7,
    servingSizeInfo: "1 bát nhỏ (~100g)",
    description: "Thực phẩm giàu đạm thực vật, thanh lọc cơ thể và điều hòa cholesterol phác đồ lành mạnh."
  },
  {
    id: "plant_olive_oil",
    name: "Dầu ô-liu (Olive Oil)",
    type: "plant",
    category: "Chất béo & Dầu ăn",
    calories: 884,
    potassium: 1,
    protein: 0.0,
    fat: 100.0,
    carbs: 0.0,
    servingSizeInfo: "1 muỗng canh (~14g)",
    description: "Nguồn chất béo cực tốt dồi dào axit béo không bão hòa đơn (Oleic acid), bảo vệ tim mạch, giảm xơ vữa động mạch."
  },
  {
    id: "plant_soybean_oil",
    name: "Dầu đậu nành",
    type: "plant",
    category: "Chất béo & Dầu ăn",
    calories: 884,
    potassium: 0,
    protein: 0.0,
    fat: 100.0,
    carbs: 0.0,
    servingSizeInfo: "1 muỗng canh (~14g)",
    description: "Dầu ăn phổ biến chiết xuất từ hạt đậu nành, giàu axit béo omega-6 và omega-3 có lợi cho tuần hoàn máu."
  },
  {
    id: "plant_coconut_oil",
    name: "Dầu dừa nguyên chất",
    type: "plant",
    category: "Chất béo & Dầu ăn",
    calories: 862,
    potassium: 0,
    protein: 0.0,
    fat: 100.0,
    carbs: 0.0,
    servingSizeInfo: "1 muỗng canh (~14g)",
    description: "Dầu dừa giàu chất béo chuỗi trung bình (MCT), dễ hấp thu giải phóng năng lượng nhanh chóng, rất bền nhiệt khi nấu nướng."
  },
  {
    id: "plant_sesame_oil",
    name: "Dầu mè thơm (Dầu vừng)",
    type: "plant",
    category: "Chất béo & Dầu ăn",
    calories: 884,
    potassium: 0,
    protein: 0.0,
    fat: 100.0,
    carbs: 0.0,
    servingSizeInfo: "1 muỗng canh (~14g)",
    description: "Hương vị dậy mùi thơm béo tự nhiên đặc trưng, chứa dồi dào chất chống oxy hóa sesamol và sesaminol cực tốt."
  },

  // --- ĐỘNG VẬT (ANIMAL BASED) ---
  {
    id: "animal_chicken_breast",
    name: "Ức gà phi lê (không da)",
    type: "animal",
    category: "Thịt",
    calories: 165,
    potassium: 256,
    protein: 31.0,
    fat: 3.6,
    carbs: 0.0,
    servingSizeInfo: "1 miếng phi lê (~100g)",
    description: "Tiêu chuẩn vàng cho đạm động vật tinh khiết siêu ít chất béo, phù hợp tăng cơ giảm mỡ."
  },
  {
    id: "animal_beef",
    name: "Thịt bò thăn nạc",
    type: "animal",
    category: "Thịt",
    calories: 250,
    potassium: 318,
    protein: 26.0,
    fat: 15.0,
    carbs: 0.0,
    servingSizeInfo: "1 lát mỏng (~100g)",
    description: "Giàu đạm, sắt heme dễ hấp thụ, kẽm và các vitamin nhóm B tốt cho thần kinh."
  },
  {
    id: "animal_salmon",
    name: "Cá hồi phi lê",
    type: "animal",
    category: "Hải sản",
    calories: 208,
    potassium: 363,
    protein: 20.0,
    fat: 13.0,
    carbs: 0.0,
    servingSizeInfo: "1 khoanh cá (~100g)",
    description: "Cung cấp dồi dào chất béo tốt Omega-3 tốt cho tim mạch và kháng viêm dồi dào Kali."
  },
  {
    id: "animal_egg",
    name: "Trứng gà tươi",
    type: "animal",
    category: "Trứng",
    calories: 155,
    potassium: 138,
    protein: 13.0,
    fat: 11.0,
    carbs: 1.1,
    servingSizeInfo: "2 quả trung bình (~100g)",
    description: "Nguồn đạm động vật sinh học hoàn hảo, sở hữu cấu trúc lipid lành mạnh và vitamin D."
  },
  {
    id: "animal_pork",
    name: "Thịt heo thăn nạc",
    type: "animal",
    category: "Thịt",
    calories: 145,
    potassium: 340,
    protein: 21.0,
    fat: 6.0,
    carbs: 0.0,
    servingSizeInfo: "1 lát thăn (~100g)",
    description: "Giàu vitamin B1 (Thiamine), đạm tốt, chất béo ở mức trung bình vừa mắt."
  },
  {
    id: "animal_shrimp",
    name: "Tôm sú hấp",
    type: "animal",
    category: "Hải sản",
    calories: 99,
    potassium: 260,
    protein: 24.0,
    fat: 0.3,
    carbs: 0.2,
    servingSizeInfo: "6-8 con tôm (~100g)",
    description: "Cung cấp đạm nạc quý từ đại dương, rất ít chất béo, giàu selenium và canxi."
  },
  {
    id: "animal_milk",
    name: "Sữa tươi không đường",
    type: "animal",
    category: "Sữa & Sản phẩm từ Sữa",
    calories: 61,
    potassium: 150,
    protein: 3.2,
    fat: 3.3,
    carbs: 4.8,
    servingSizeInfo: "1 ly sữa uống (~100ml)",
    description: "Bổ sung lượng canxi tuyệt vời hàng ngày kèm Kali sinh học tương tác cơ."
  },
  {
    id: "animal_yogurt",
    name: "Sữa chua không đường",
    type: "animal",
    category: "Sữa & Sản phẩm từ Sữa",
    calories: 59,
    potassium: 141,
    protein: 3.5,
    fat: 3.2,
    carbs: 4.7,
    servingSizeInfo: "1 hũ (~100g)",
    description: "Chứa nhiều lợi khuẩn probiotics thúc đẩy hệ tiêu hóa khỏe mạnh, đạm cân bằng."
  },
  {
    id: "animal_tuna",
    name: "Cá ngừ đại dương",
    type: "animal",
    category: "Hải sản",
    calories: 132,
    potassium: 441,
    protein: 28.0,
    fat: 1.3,
    carbs: 0.0,
    servingSizeInfo: "1 lát cá phi lê (~100g)",
    description: "Hàm lượng đạm rất cao kết tinh nạc biển sâu, cực giàu vitamin B12 và chứa Kali đáng kính."
  },
  {
    id: "animal_mackerel",
    name: "Cá thu tươi",
    type: "animal",
    category: "Hải sản",
    calories: 189,
    potassium: 446,
    protein: 19.0,
    fat: 12.0,
    carbs: 0.0,
    servingSizeInfo: "1 khoanh cá (~100g)",
    description: "Cá thu dồi dào chất béo omega-3 dẻo dai hỗ trợ tim mạch, chứa lượng đạm dồi dào và hàm lượng Kali cao."
  },
  {
    id: "animal_anchovy",
    name: "Cá cơm tươi",
    type: "animal",
    category: "Hải sản",
    calories: 131,
    potassium: 383,
    protein: 20.0,
    fat: 4.8,
    carbs: 0.0,
    servingSizeInfo: "Khẩu phần nhỏ (~100g)",
    description: "Cá biển nhỏ ăn được cả xương giúp bổ sung canxi và phốt pho dồi dào, hàm lượng đạm tốt và giàu Kali tự nhiên."
  },
  {
    id: "animal_round_scad",
    name: "Cá nục",
    type: "animal",
    category: "Hải sản",
    calories: 121,
    potassium: 360,
    protein: 20.2,
    fat: 3.5,
    carbs: 0.0,
    servingSizeInfo: "1 con vừa (~100g)",
    description: "Cá nục chứa nguồn đạm nạc phong phú, chất béo có ích cho sức khỏe, ổn định huyết áp cho cơ thể."
  },
  {
    id: "animal_goby",
    name: "Cá bống sông",
    type: "animal",
    category: "Hải sản",
    calories: 80,
    potassium: 250,
    protein: 15.8,
    fat: 0.8,
    carbs: 0.0,
    servingSizeInfo: "Khẩu phần (~100g)",
    description: "Cá nước ngọt vị ngọt tính bình, cực kỳ ít béo, thích hợp chế biến kho tiêu cho thực đơn thanh đạm."
  },
  {
    id: "animal_red_tilapia",
    name: "Cá diêu hồng",
    type: "animal",
    category: "Hải sản",
    calories: 120,
    potassium: 302,
    protein: 20.0,
    fat: 3.0,
    carbs: 0.0,
    servingSizeInfo: "1 miếng phi lê (~100g)",
    description: "Thịt cá diêu hồng trắng thơm ngọt, dễ tiêu hóa, thích hợp bồi bổ sức khỏe cho mọi lứa tuổi."
  }
];
